name: TF Pre-Commit

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  main:
    uses: getindata/github-workflows/.github/workflows/tf-pre-commit.yml@v1
    with:
      tflint-version: v0.49.0
